image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf &&
      echo "experimental-features = nix-command flakes" >> /home/gitpod/.config/nix/nix.conf &&
      direnv allow .

vscode:
  extensions:
    # Nix
    - jnoortheen.nix-ide
    - mkhl.direnv

    # Go
    - golang.Go

    # Build
    - skellock.just

    # Other
    - bungcip.better-toml
